export const data = {
  items: [
    {
      id: 1,
      name: "MOOC  System",
      description: "We have made a platform where can we place all the high rated courses in a single platform",
      tools: "HTML, CSS, Javascript, Bootstrap",
      code: "https://github.com/TahirAli32/firebase-chat",
      live: "https://chat-app-by-dc.netlify.app/",
    },
    {
      id: 2,
      name: "Todo List",
      description: "I have made a todolist where we can create add edit and delete todo by using of JSON",
      code: "https://github.com/TahirAli32/firebase-chat",
      tools: "HTML, CSS, Javascript, Vuejs, Vuex, Testutils, RestAPI, JSON",
      live: "https://chat-app-by-dc.netlify.app/",
    },
    {
      id: 3,
      name: "Freshly Clone",
      description: "FReshly is meal website, we just made a clone of this.",
      tools: "HTML, CSS, Javascript, Bootstrap, React,",
      code: "https://github.com/TahirAli32/firebase-chat",
      live: "https://chat-app-by-dc.netlify.app/",
    },
    {
      id: 4,
      name: "Orbitz Clone",
      description: "We have made clone of Orbitz",
      tools: "HTML, CSS, Javascript, Bootstrap, React",
      code: "https://github.com/TahirAli32/firebase-chat",
      live: "https://chat-app-by-dc.netlify.app/",
    },
    {
      id: 5,
      name: "Firstpost Clone",
      description: "It is a news based website i have made a clone of this website by using React",
      tools: "HTML, CSS, Javascript, Bootstrap, React, Redux",
      code: "https://github.com/TahirAli32/firebase-chat",
      live: "https://chat-app-by-dc.netlify.app/",
    },
    {
      id: 6,
      name: "abc",
      description: "This is the third item.",
      tools: "HTML, CSS, Javascript, Bootstrap",
      code: "https://github.com/TahirAli32/firebase-chat",
      live: "https://chat-app-by-dc.netlify.app/",
    },
  ],
};
